<a href="https://colab.research.google.com/github/shivs2000/tensorflow_basic/blob/main/tf_overview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
x=tf.constant([[1,2,3] ,[4,5,6]])
print(x)
print(x.dtype)
print(x.shape)

#checking the normal operations on tensors
print(x+x)
print(5*x)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
<dtype: 'int32'>
(2, 3)
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 5 10 15]
 [20 25 30]], shape=(2, 3), dtype=int32)


In [2]:
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [3]:
tf.concat([x,x,x],axis=0)

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

TO CHECK ALL SUPPORTED DTYPE


In [4]:
tf.dtypes.DType

tensorflow.python.framework.dtypes.DType

Converting a tensor to Numpy array


In [5]:
import numpy as np
np.array(x)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [6]:
x.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)